name: FYP_Env
channels:
  - defaults
  - conda-forge  # Add conda-forge for broader package support
dependencies:
  - python=3.9
  - pip
  - numpy=1.23.5
  - matplotlib
  - pandas
  - jupyterlab
  - cudatoolkit=11.2  # Only if GPU is intended; remove if not applicable
  - cudnn=8.1         # Only if GPU is intended; remove if not applicable
  - pip:
    - tensorflow[and-cuda]==2.15.1
    - tensorflow-addons  # Optional, for additional TensorFlow features
    - sklearn
    - datasets
    - transformers

